import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#2f3b44",
        "on-primary-fixed": "#002201",
        "on-secondary-fixed": "#390c00",
        "on-primary-container": "#9dd090",
        outline: "#72796e",
        "on-tertiary-container": "#b8c5d0",
        "secondary-container": "#fe6a34",
        primary: "#154212",
        "on-error-container": "#93000a",
        "surface-container": "#e3effb",
        "primary-fixed": "#bcf0ae",
        "on-primary-fixed-variant": "#23501e",
        "tertiary-container": "#46525b",
        "surface-tint": "#3b6934",
        "inverse-on-surface": "#e6f2fe",
        "tertiary-fixed-dim": "#bbc8d3",
        "surface-dim": "#cfdce7",
        "on-error": "#ffffff",
        "surface-container-high": "#ddeaf5",
        "secondary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#a1d494",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-surface": "#111d25",
        background: "#f6faff",
        "inverse-surface": "#26323b",
        "surface-container-low": "#eaf5ff",
        "secondary-fixed-dim": "#ffb59d",
        "on-primary": "#ffffff",
        "on-surface-variant": "#42493e",
        "outline-variant": "#c2c9bb",
        "surface-bright": "#f6faff",
        "on-tertiary-fixed": "#111d25",
        "on-background": "#111d25",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-variant": "#d7e4f0",
        "on-secondary-container": "#5d1900",
        "on-secondary-fixed-variant": "#832600",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
